apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/xiaoluo/kindm
        containerPath: /data
    # kubeadmConfigPatches:
    #   - |
    #     kind: InitConfiguration
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         node-labels: "ingress-ready=true"
    # extraPortMappings:
    # - containerPort: 80
    #   hostPort: 80
    #   protocol: TCP
    # - containerPort: 443
    #   hostPort: 443
    #   protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /Users/xiaoluo/kindm
        containerPath: /data
  - role: worker
    extraMounts:
      - hostPath: /Users/xiaoluo/kindm
        containerPath: /data
        